# Generated by Django 4.1.7 on 2023-03-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='time',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
